CREATE DATABASE IF NOT EXISTS appDB;
-- CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
-- GRANT SELECT,UPDATE,INSERT ON appDB.* TO 'user'@'%';
FLUSH PRIVILEGES;

USE appDB;
CREATE TABLE IF NOT EXISTS students (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL
);