server:
  port: '80'
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
    platform: postgres
  sql:
    init:
      platform: postgresql
      mode: always
